CREATE TYPE public.app_role AS ENUM ('INVENTORY_MANAGER','WAREHOUSE_STAFF');
CREATE TYPE public.operation_type AS ENUM ('RECEIPT','DELIVERY','INTERNAL_TRANSFER','ADJUSTMENT');
CREATE TYPE public.operation_status AS ENUM ('DRAFT','WAITING','READY','DONE','CANCELED');
CREATE TYPE public.partner_type AS ENUM ('SUPPLIER','CUSTOMER');
CREATE TYPE public.location_type AS ENUM ('INTERNAL','VENDOR','CUSTOMER','ADJUSTMENT_VIRTUAL');

CREATE TABLE public.warehouses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(120) NOT NULL,
  code varchar(20) NOT NULL UNIQUE,
  address text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.locations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  warehouse_id bigint REFERENCES public.warehouses(id),
  parent_location_id bigint REFERENCES public.locations(id),
  name varchar(120) NOT NULL,
  code varchar(30) NOT NULL,
  location_type public.location_type NOT NULL DEFAULT 'INTERNAL',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.product_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  parent_category_id bigint REFERENCES public.product_categories(id),
  is_active boolean NOT NULL DEFAULT true
);
CREATE TABLE public.units_of_measure (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(40) NOT NULL,
  code varchar(10) NOT NULL,
  is_active boolean NOT NULL DEFAULT true
);
CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(150) NOT NULL,
  sku varchar(60) NOT NULL UNIQUE,
  barcode varchar(60),
  category_id bigint NOT NULL REFERENCES public.product_categories(id),
  uom_id bigint NOT NULL REFERENCES public.units_of_measure(id),
  unit_cost numeric(14,2) NOT NULL DEFAULT 0,
  description text,
  reorder_min_qty numeric(14,3) NOT NULL DEFAULT 0,
  reorder_max_qty numeric(14,3),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.partners (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(150) NOT NULL,
  type public.partner_type NOT NULL,
  email varchar(160),
  phone varchar(20),
  address text,
  is_active boolean NOT NULL DEFAULT true
);
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY,
  login_id varchar(60) NOT NULL UNIQUE,
  email varchar(160) NOT NULL UNIQUE,
  full_name varchar(120),
  phone varchar(20),
  warehouse_id bigint REFERENCES public.warehouses(id),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL,
  UNIQUE (user_id, role)
);
CREATE TABLE public.stock_operations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_no varchar(30) NOT NULL UNIQUE,
  operation_type public.operation_type NOT NULL,
  status public.operation_status NOT NULL DEFAULT 'DRAFT',
  warehouse_id bigint NOT NULL REFERENCES public.warehouses(id),
  source_location_id bigint REFERENCES public.locations(id),
  destination_location_id bigint REFERENCES public.locations(id),
  partner_id bigint REFERENCES public.partners(id),
  scheduled_date timestamptz NOT NULL DEFAULT now(),
  validated_date timestamptz,
  created_by uuid NOT NULL,
  responsible_user_id uuid,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.stock_operation_lines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id bigint NOT NULL REFERENCES public.stock_operations(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES public.products(id),
  uom_id bigint NOT NULL REFERENCES public.units_of_measure(id),
  quantity_planned numeric(14,3) NOT NULL DEFAULT 0,
  quantity_done numeric(14,3) NOT NULL DEFAULT 0,
  notes text
);
CREATE TABLE public.stock_adjustment_lines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id bigint NOT NULL REFERENCES public.stock_operations(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES public.products(id),
  location_id bigint NOT NULL REFERENCES public.locations(id),
  uom_id bigint NOT NULL REFERENCES public.units_of_measure(id),
  recorded_quantity numeric(14,3) NOT NULL DEFAULT 0,
  counted_quantity numeric(14,3) NOT NULL DEFAULT 0,
  difference numeric(14,3) NOT NULL DEFAULT 0
);
CREATE TABLE public.stock_quants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id),
  location_id bigint NOT NULL REFERENCES public.locations(id),
  quantity numeric(14,3) NOT NULL DEFAULT 0,
  reserved_quantity numeric(14,3) NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (product_id, location_id)
);
CREATE TABLE public.stock_ledger_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id),
  location_id bigint NOT NULL REFERENCES public.locations(id),
  quantity_change numeric(14,3) NOT NULL,
  balance_after numeric(14,3) NOT NULL,
  operation_id bigint NOT NULL REFERENCES public.stock_operations(id),
  operation_type public.operation_type NOT NULL,
  reference_no varchar(30) NOT NULL,
  movement_date timestamptz NOT NULL DEFAULT now(),
  created_by uuid
);
CREATE TABLE public.operation_sequences (
  warehouse_id bigint NOT NULL REFERENCES public.warehouses(id),
  op_code varchar(5) NOT NULL,
  last_value int NOT NULL DEFAULT 0,
  PRIMARY KEY (warehouse_id, op_code)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.warehouses, public.locations, public.product_categories, public.units_of_measure, public.products, public.partners TO authenticated;
GRANT SELECT, UPDATE ON public.profiles TO authenticated;
GRANT SELECT ON public.user_roles, public.stock_operations, public.stock_operation_lines, public.stock_adjustment_lines, public.stock_quants, public.stock_ledger_entries TO authenticated;
GRANT ALL ON public.warehouses, public.locations, public.product_categories, public.units_of_measure, public.products, public.partners, public.profiles, public.user_roles, public.stock_operations, public.stock_operation_lines, public.stock_adjustment_lines, public.stock_quants, public.stock_ledger_entries, public.operation_sequences TO service_role;

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role)
$$;
CREATE OR REPLACE FUNCTION public.is_manager() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.has_role(auth.uid(), 'INVENTORY_MANAGER')
$$;

ALTER TABLE public.warehouses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.units_of_measure ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_operations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_operation_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_adjustment_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_quants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_ledger_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operation_sequences ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['warehouses','locations','product_categories','units_of_measure','products','partners'] LOOP
    EXECUTE format('CREATE POLICY "read %1$s" ON public.%1$I FOR SELECT TO authenticated USING (true)', t);
    EXECUTE format('CREATE POLICY "managers insert %1$s" ON public.%1$I FOR INSERT TO authenticated WITH CHECK (public.is_manager())', t);
    EXECUTE format('CREATE POLICY "managers update %1$s" ON public.%1$I FOR UPDATE TO authenticated USING (public.is_manager()) WITH CHECK (public.is_manager())', t);
  END LOOP;
  FOREACH t IN ARRAY ARRAY['stock_operations','stock_operation_lines','stock_adjustment_lines','stock_quants','stock_ledger_entries','user_roles'] LOOP
    EXECUTE format('CREATE POLICY "read %1$s" ON public.%1$I FOR SELECT TO authenticated USING (true)', t);
  END LOOP;
END $$;

CREATE POLICY "read profiles" ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "update own profile" ON public.profiles FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());

CREATE OR REPLACE FUNCTION public.protect_profile_fields() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF current_setting('app.bypass', true) = 'on' THEN RETURN NEW; END IF;
  NEW.login_id := OLD.login_id;
  NEW.email := OLD.email;
  NEW.warehouse_id := OLD.warehouse_id;
  NEW.is_active := OLD.is_active;
  NEW.updated_at := now();
  RETURN NEW;
END $$;
CREATE TRIGGER profiles_protect BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.protect_profile_fields();

CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_login text;
BEGIN
  v_login := COALESCE(NULLIF(NEW.raw_user_meta_data->>'login_id',''), split_part(NEW.email,'@',1));
  INSERT INTO public.profiles (id, login_id, email) VALUES (NEW.id, v_login, NEW.email);
  IF NOT EXISTS (SELECT 1 FROM public.user_roles WHERE role = 'INVENTORY_MANAGER') THEN
    INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'INVENTORY_MANAGER');
  ELSE
    INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'WAREHOUSE_STAFF');
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION public.email_for_login(_login_id text) RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT email FROM public.profiles WHERE lower(login_id) = lower(_login_id) AND is_active LIMIT 1
$$;
CREATE OR REPLACE FUNCTION public.check_signup_available(_login_id text, _email text) RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT CASE
    WHEN EXISTS (SELECT 1 FROM public.profiles WHERE lower(login_id) = lower(_login_id)) THEN 'LOGIN_ID_TAKEN'
    WHEN EXISTS (SELECT 1 FROM public.profiles WHERE lower(email) = lower(_email)) THEN 'EMAIL_TAKEN'
    ELSE 'OK' END
$$;
GRANT EXECUTE ON FUNCTION public.email_for_login(text), public.check_signup_available(text,text) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.admin_update_user(_user_id uuid, _role public.app_role, _warehouse_id bigint, _is_active boolean)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.is_manager() THEN RAISE EXCEPTION 'FORBIDDEN: Only managers can manage users'; END IF;
  IF _user_id = auth.uid() AND _role <> 'INVENTORY_MANAGER' THEN RAISE EXCEPTION 'You cannot demote yourself'; END IF;
  DELETE FROM public.user_roles WHERE user_id = _user_id;
  INSERT INTO public.user_roles (user_id, role) VALUES (_user_id, _role);
  PERFORM set_config('app.bypass','on', true);
  UPDATE public.profiles SET warehouse_id = _warehouse_id, is_active = _is_active, updated_at = now() WHERE id = _user_id;
  PERFORM set_config('app.bypass','off', true);
END $$;

CREATE OR REPLACE FUNCTION public.op_code(_t public.operation_type) RETURNS text LANGUAGE sql IMMUTABLE SET search_path = public AS $$
  SELECT CASE _t WHEN 'RECEIPT' THEN 'IN' WHEN 'DELIVERY' THEN 'OUT' WHEN 'INTERNAL_TRANSFER' THEN 'INT' ELSE 'ADJ' END
$$;

CREATE OR REPLACE FUNCTION public.next_reference(_wh bigint, _t public.operation_type) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_code text := public.op_code(_t); v_n int; v_wh text;
BEGIN
  SELECT code INTO v_wh FROM public.warehouses WHERE id = _wh;
  IF v_wh IS NULL THEN RAISE EXCEPTION 'Warehouse not found'; END IF;
  INSERT INTO public.operation_sequences (warehouse_id, op_code, last_value) VALUES (_wh, v_code, 1)
  ON CONFLICT (warehouse_id, op_code) DO UPDATE SET last_value = operation_sequences.last_value + 1
  RETURNING last_value INTO v_n;
  RETURN v_wh || '/' || v_code || '/' || lpad(v_n::text, 4, '0');
END $$;

CREATE OR REPLACE FUNCTION public.virtual_location(_t public.location_type) RETURNS bigint LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT id FROM public.locations WHERE location_type = _t ORDER BY id LIMIT 1
$$;

CREATE OR REPLACE FUNCTION public.qty_at(_product bigint, _loc bigint) RETURNS numeric LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE((SELECT quantity FROM public.stock_quants WHERE product_id = _product AND location_id = _loc), 0)
$$;

CREATE OR REPLACE FUNCTION public._apply_move(_op public.stock_operations, _product bigint, _loc bigint, _delta numeric)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_type public.location_type; v_bal numeric;
BEGIN
  IF _loc IS NULL OR _delta = 0 THEN RETURN; END IF;
  SELECT location_type INTO v_type FROM public.locations WHERE id = _loc;
  IF v_type <> 'INTERNAL' THEN RETURN; END IF;
  INSERT INTO public.stock_quants (product_id, location_id, quantity) VALUES (_product, _loc, _delta)
  ON CONFLICT (product_id, location_id) DO UPDATE SET quantity = stock_quants.quantity + _delta, updated_at = now()
  RETURNING quantity INTO v_bal;
  INSERT INTO public.stock_ledger_entries (product_id, location_id, quantity_change, balance_after, operation_id, operation_type, reference_no, movement_date, created_by)
  VALUES (_product, _loc, _delta, v_bal, _op.id, _op.operation_type, _op.reference_no, now(), auth.uid());
END $$;

CREATE OR REPLACE FUNCTION public._reserve(_product bigint, _loc bigint, _delta numeric)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF _loc IS NULL OR _delta = 0 THEN RETURN; END IF;
  INSERT INTO public.stock_quants (product_id, location_id, quantity, reserved_quantity) VALUES (_product, _loc, 0, GREATEST(_delta,0))
  ON CONFLICT (product_id, location_id) DO UPDATE SET reserved_quantity = GREATEST(stock_quants.reserved_quantity + _delta, 0), updated_at = now();
END $$;

CREATE OR REPLACE FUNCTION public._op_has_stock(_op_id bigint, _own_reserved boolean) RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE r record; v_src bigint; v_free numeric;
BEGIN
  SELECT source_location_id INTO v_src FROM public.stock_operations WHERE id = _op_id;
  FOR r IN SELECT product_id, SUM(quantity_planned) AS planned FROM public.stock_operation_lines WHERE operation_id = _op_id GROUP BY product_id LOOP
    v_free := NULL;
    SELECT quantity - reserved_quantity INTO v_free FROM public.stock_quants WHERE product_id = r.product_id AND location_id = v_src;
    v_free := COALESCE(v_free, 0) + CASE WHEN _own_reserved THEN r.planned ELSE 0 END;
    IF r.planned > v_free THEN RETURN false; END IF;
  END LOOP;
  RETURN true;
END $$;

CREATE OR REPLACE FUNCTION public.refresh_waiting() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE r record;
BEGIN
  FOR r IN SELECT id FROM public.stock_operations WHERE status = 'WAITING' ORDER BY scheduled_date LOOP
    IF public._op_has_stock(r.id, true) THEN
      UPDATE public.stock_operations SET status = 'READY', updated_at = now() WHERE id = r.id;
    END IF;
  END LOOP;
END $$;

CREATE OR REPLACE FUNCTION public.create_operation(_payload jsonb) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_type public.operation_type := (_payload->>'operation_type')::public.operation_type;
  v_wh bigint := NULLIF(_payload->>'warehouse_id','')::bigint;
  v_src bigint := NULLIF(_payload->>'source_location_id','')::bigint;
  v_dst bigint := NULLIF(_payload->>'destination_location_id','')::bigint;
  v_partner bigint := NULLIF(_payload->>'partner_id','')::bigint;
  v_resp uuid := COALESCE(NULLIF(_payload->>'responsible_user_id','')::uuid, auth.uid());
  v_id bigint; l jsonb; v_uom bigint; v_qty numeric;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'UNAUTHORIZED'; END IF;
  IF v_type = 'RECEIPT' AND NOT public.is_manager() THEN RAISE EXCEPTION 'FORBIDDEN: Only managers can create receipts'; END IF;
  IF v_resp <> auth.uid() AND NOT public.is_manager() THEN v_resp := auth.uid(); END IF;
  IF v_wh IS NULL THEN RAISE EXCEPTION 'Warehouse is required'; END IF;
  IF jsonb_array_length(COALESCE(_payload->'lines','[]'::jsonb)) = 0 THEN RAISE EXCEPTION 'Add at least one product line'; END IF;

  IF v_type = 'RECEIPT' THEN
    IF v_partner IS NULL THEN RAISE EXCEPTION 'Supplier is required'; END IF;
    IF v_dst IS NULL THEN RAISE EXCEPTION 'Destination location is required'; END IF;
    v_src := public.virtual_location('VENDOR');
  ELSIF v_type = 'DELIVERY' THEN
    IF v_partner IS NULL THEN RAISE EXCEPTION 'Customer is required'; END IF;
    IF v_src IS NULL THEN RAISE EXCEPTION 'Source location is required'; END IF;
    v_dst := public.virtual_location('CUSTOMER');
  ELSIF v_type = 'INTERNAL_TRANSFER' THEN
    IF v_src IS NULL OR v_dst IS NULL THEN RAISE EXCEPTION 'Source and destination are required'; END IF;
    IF v_src = v_dst THEN RAISE EXCEPTION 'Source and destination must differ'; END IF;
    v_partner := NULL;
  ELSE
    v_src := NULL; v_dst := NULL; v_partner := NULL;
  END IF;

  INSERT INTO public.stock_operations (reference_no, operation_type, warehouse_id, source_location_id, destination_location_id, partner_id, scheduled_date, created_by, responsible_user_id, notes)
  VALUES (public.next_reference(v_wh, v_type), v_type, v_wh, v_src, v_dst, v_partner,
          COALESCE(NULLIF(_payload->>'scheduled_date','')::timestamptz, now()), auth.uid(), v_resp, _payload->>'notes')
  RETURNING id INTO v_id;

  FOR l IN SELECT * FROM jsonb_array_elements(_payload->'lines') LOOP
    v_uom := NULL;
    SELECT uom_id INTO v_uom FROM public.products WHERE id = (l->>'product_id')::bigint;
    IF v_uom IS NULL THEN RAISE EXCEPTION 'Unknown product'; END IF;
    IF v_type = 'ADJUSTMENT' THEN
      IF NULLIF(l->>'location_id','') IS NULL THEN RAISE EXCEPTION 'Each adjustment line needs a location'; END IF;
      IF COALESCE((l->>'counted_quantity')::numeric,0) < 0 THEN RAISE EXCEPTION 'Counted quantity cannot be negative'; END IF;
      v_qty := public.qty_at((l->>'product_id')::bigint, (l->>'location_id')::bigint);
      INSERT INTO public.stock_adjustment_lines (operation_id, product_id, location_id, uom_id, recorded_quantity, counted_quantity, difference)
      VALUES (v_id, (l->>'product_id')::bigint, (l->>'location_id')::bigint, v_uom, v_qty, COALESCE((l->>'counted_quantity')::numeric,0), COALESCE((l->>'counted_quantity')::numeric,0) - v_qty);
    ELSE
      IF COALESCE((l->>'quantity_planned')::numeric,0) <= 0 THEN RAISE EXCEPTION 'Quantity must be greater than 0'; END IF;
      INSERT INTO public.stock_operation_lines (operation_id, product_id, uom_id, quantity_planned, quantity_done)
      VALUES (v_id, (l->>'product_id')::bigint, v_uom, (l->>'quantity_planned')::numeric,
              COALESCE((l->>'quantity_done')::numeric, (l->>'quantity_planned')::numeric));
    END IF;
  END LOOP;
  RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION public.update_operation(_id bigint, _payload jsonb) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_op public.stock_operations; l jsonb; v_uom bigint; v_qty numeric;
BEGIN
  SELECT * INTO v_op FROM public.stock_operations WHERE id = _id FOR UPDATE;
  IF v_op.id IS NULL THEN RAISE EXCEPTION 'Operation not found'; END IF;
  IF v_op.status IN ('DONE','CANCELED') THEN RAISE EXCEPTION 'OPERATION_LOCKED: Done or canceled operations cannot be edited'; END IF;
  IF v_op.operation_type = 'RECEIPT' AND NOT public.is_manager() AND v_op.status = 'DRAFT' THEN RAISE EXCEPTION 'FORBIDDEN: Only managers can edit draft receipts'; END IF;

  IF _payload ? 'responsible_user_id' AND NULLIF(_payload->>'responsible_user_id','')::uuid IS DISTINCT FROM v_op.responsible_user_id THEN
    IF NOT public.is_manager() THEN RAISE EXCEPTION 'FORBIDDEN: Only managers can reassign responsible'; END IF;
    UPDATE public.stock_operations SET responsible_user_id = NULLIF(_payload->>'responsible_user_id','')::uuid WHERE id = _id;
  END IF;
  IF v_op.status = 'DRAFT' THEN
    UPDATE public.stock_operations SET
      scheduled_date = COALESCE(NULLIF(_payload->>'scheduled_date','')::timestamptz, scheduled_date),
      partner_id = CASE WHEN operation_type IN ('RECEIPT','DELIVERY') AND NULLIF(_payload->>'partner_id','') IS NOT NULL THEN (_payload->>'partner_id')::bigint ELSE partner_id END,
      source_location_id = CASE WHEN operation_type IN ('DELIVERY','INTERNAL_TRANSFER') AND NULLIF(_payload->>'source_location_id','') IS NOT NULL THEN (_payload->>'source_location_id')::bigint ELSE source_location_id END,
      destination_location_id = CASE WHEN operation_type IN ('RECEIPT','INTERNAL_TRANSFER') AND NULLIF(_payload->>'destination_location_id','') IS NOT NULL THEN (_payload->>'destination_location_id')::bigint ELSE destination_location_id END
    WHERE id = _id;
  END IF;
  UPDATE public.stock_operations SET notes = COALESCE(_payload->>'notes', notes), updated_at = now() WHERE id = _id;

  IF _payload ? 'lines' THEN
    IF jsonb_array_length(_payload->'lines') = 0 THEN RAISE EXCEPTION 'Add at least one product line'; END IF;
    IF v_op.operation_type = 'ADJUSTMENT' THEN
      DELETE FROM public.stock_adjustment_lines WHERE operation_id = _id;
      FOR l IN SELECT * FROM jsonb_array_elements(_payload->'lines') LOOP
        SELECT uom_id INTO v_uom FROM public.products WHERE id = (l->>'product_id')::bigint;
        v_qty := public.qty_at((l->>'product_id')::bigint, (l->>'location_id')::bigint);
        INSERT INTO public.stock_adjustment_lines (operation_id, product_id, location_id, uom_id, recorded_quantity, counted_quantity, difference)
        VALUES (_id, (l->>'product_id')::bigint, (l->>'location_id')::bigint, v_uom, v_qty, COALESCE((l->>'counted_quantity')::numeric,0), COALESCE((l->>'counted_quantity')::numeric,0) - v_qty);
      END LOOP;
    ELSIF v_op.status = 'DRAFT' THEN
      DELETE FROM public.stock_operation_lines WHERE operation_id = _id;
      FOR l IN SELECT * FROM jsonb_array_elements(_payload->'lines') LOOP
        SELECT uom_id INTO v_uom FROM public.products WHERE id = (l->>'product_id')::bigint;
        IF COALESCE((l->>'quantity_planned')::numeric,0) <= 0 THEN RAISE EXCEPTION 'Quantity must be greater than 0'; END IF;
        INSERT INTO public.stock_operation_lines (operation_id, product_id, uom_id, quantity_planned, quantity_done)
        VALUES (_id, (l->>'product_id')::bigint, v_uom, (l->>'quantity_planned')::numeric, COALESCE((l->>'quantity_done')::numeric, (l->>'quantity_planned')::numeric));
      END LOOP;
    ELSE
      FOR l IN SELECT * FROM jsonb_array_elements(_payload->'lines') LOOP
        IF COALESCE((l->>'quantity_done')::numeric,0) < 0 THEN RAISE EXCEPTION 'Done quantity cannot be negative'; END IF;
        UPDATE public.stock_operation_lines SET quantity_done = COALESCE((l->>'quantity_done')::numeric,0)
        WHERE id = (l->>'id')::bigint AND operation_id = _id;
      END LOOP;
    END IF;
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.confirm_operation(_id bigint) RETURNS public.operation_status LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_op public.stock_operations; v_new public.operation_status; r record;
BEGIN
  SELECT * INTO v_op FROM public.stock_operations WHERE id = _id FOR UPDATE;
  IF v_op.id IS NULL THEN RAISE EXCEPTION 'Operation not found'; END IF;
  IF v_op.status <> 'DRAFT' THEN RAISE EXCEPTION 'INVALID_STATUS: Only draft operations can be confirmed'; END IF;
  IF v_op.operation_type = 'RECEIPT' AND NOT public.is_manager() THEN RAISE EXCEPTION 'FORBIDDEN: Only managers can confirm receipts'; END IF;

  IF v_op.operation_type IN ('DELIVERY','INTERNAL_TRANSFER') THEN
    v_new := CASE WHEN public._op_has_stock(_id, false) THEN 'READY'::public.operation_status ELSE 'WAITING'::public.operation_status END;
    FOR r IN SELECT product_id, quantity_planned FROM public.stock_operation_lines WHERE operation_id = _id LOOP
      PERFORM public._reserve(r.product_id, v_op.source_location_id, r.quantity_planned);
    END LOOP;
  ELSE
    v_new := 'READY';
    IF v_op.operation_type = 'ADJUSTMENT' THEN
      UPDATE public.stock_adjustment_lines SET recorded_quantity = public.qty_at(product_id, location_id),
        difference = counted_quantity - public.qty_at(product_id, location_id) WHERE operation_id = _id;
    END IF;
  END IF;
  UPDATE public.stock_operations SET status = v_new, updated_at = now() WHERE id = _id;
  RETURN v_new;
END $$;

CREATE OR REPLACE FUNCTION public.validate_operation(_id bigint) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_op public.stock_operations; r record; v_avail numeric; v_rec numeric;
BEGIN
  SELECT * INTO v_op FROM public.stock_operations WHERE id = _id FOR UPDATE;
  IF v_op.id IS NULL THEN RAISE EXCEPTION 'Operation not found'; END IF;
  IF v_op.status = 'WAITING' THEN
    IF public._op_has_stock(_id, true) THEN
      UPDATE public.stock_operations SET status = 'READY' WHERE id = _id; v_op.status := 'READY';
    ELSE RAISE EXCEPTION 'INSUFFICIENT_STOCK: Still waiting for stock at the source location'; END IF;
  END IF;
  IF v_op.status <> 'READY' THEN RAISE EXCEPTION 'INVALID_STATUS: Only ready operations can be validated'; END IF;

  IF v_op.operation_type = 'ADJUSTMENT' THEN
    FOR r IN SELECT * FROM public.stock_adjustment_lines WHERE operation_id = _id LOOP
      v_rec := public.qty_at(r.product_id, r.location_id);
      UPDATE public.stock_adjustment_lines SET recorded_quantity = v_rec, difference = r.counted_quantity - v_rec WHERE id = r.id;
      PERFORM public._apply_move(v_op, r.product_id, r.location_id, r.counted_quantity - v_rec);
    END LOOP;
  ELSE
    IF NOT EXISTS (SELECT 1 FROM public.stock_operation_lines WHERE operation_id = _id AND quantity_done > 0) THEN
      RAISE EXCEPTION 'NO_QUANTITY_DONE: Set a done quantity on at least one line';
    END IF;
    IF v_op.operation_type IN ('DELIVERY','INTERNAL_TRANSFER') THEN
      FOR r IN SELECT product_id, SUM(quantity_done) AS done FROM public.stock_operation_lines WHERE operation_id = _id GROUP BY product_id LOOP
        v_avail := public.qty_at(r.product_id, v_op.source_location_id);
        IF r.done > v_avail THEN
          RAISE EXCEPTION 'INSUFFICIENT_STOCK: Only % available at source for %', v_avail, (SELECT sku FROM public.products WHERE id = r.product_id);
        END IF;
      END LOOP;
    END IF;
    FOR r IN SELECT * FROM public.stock_operation_lines WHERE operation_id = _id LOOP
      IF v_op.operation_type IN ('DELIVERY','INTERNAL_TRANSFER') THEN
        PERFORM public._reserve(r.product_id, v_op.source_location_id, -r.quantity_planned);
      END IF;
      IF r.quantity_done > 0 THEN
        PERFORM public._apply_move(v_op, r.product_id, v_op.source_location_id, -r.quantity_done);
        PERFORM public._apply_move(v_op, r.product_id, v_op.destination_location_id, r.quantity_done);
      END IF;
    END LOOP;
  END IF;
  UPDATE public.stock_operations SET status = 'DONE', validated_date = now(), updated_at = now() WHERE id = _id;
  PERFORM public.refresh_waiting();
END $$;

CREATE OR REPLACE FUNCTION public.cancel_operation(_id bigint) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_op public.stock_operations; r record;
BEGIN
  SELECT * INTO v_op FROM public.stock_operations WHERE id = _id FOR UPDATE;
  IF v_op.id IS NULL THEN RAISE EXCEPTION 'Operation not found'; END IF;
  IF v_op.status IN ('DONE','CANCELED') THEN RAISE EXCEPTION 'INVALID_STATUS: This operation can no longer be canceled'; END IF;
  IF NOT public.is_manager() AND NOT (v_op.status = 'DRAFT' AND v_op.created_by = auth.uid()) THEN
    RAISE EXCEPTION 'FORBIDDEN: Staff can only cancel their own drafts';
  END IF;
  IF v_op.status IN ('WAITING','READY') AND v_op.operation_type IN ('DELIVERY','INTERNAL_TRANSFER') THEN
    FOR r IN SELECT product_id, quantity_planned FROM public.stock_operation_lines WHERE operation_id = _id LOOP
      PERFORM public._reserve(r.product_id, v_op.source_location_id, -r.quantity_planned);
    END LOOP;
  END IF;
  UPDATE public.stock_operations SET status = 'CANCELED', updated_at = now() WHERE id = _id;
  PERFORM public.refresh_waiting();
END $$;

CREATE OR REPLACE FUNCTION public.set_stock(_product bigint, _location bigint, _counted numeric) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_wh bigint; v_id bigint;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'UNAUTHORIZED'; END IF;
  IF _counted < 0 THEN RAISE EXCEPTION 'Quantity cannot be negative'; END IF;
  SELECT warehouse_id INTO v_wh FROM public.locations WHERE id = _location AND location_type = 'INTERNAL';
  IF v_wh IS NULL THEN RAISE EXCEPTION 'Pick an internal warehouse location'; END IF;
  v_id := public.create_operation(jsonb_build_object('operation_type','ADJUSTMENT','warehouse_id',v_wh,'notes','Quick stock update',
    'lines', jsonb_build_array(jsonb_build_object('product_id',_product,'location_id',_location,'counted_quantity',_counted))));
  PERFORM public.confirm_operation(v_id);
  PERFORM public.validate_operation(v_id);
  RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION public.guard_soft_delete() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF OLD.is_active AND NOT NEW.is_active THEN
    IF TG_TABLE_NAME = 'products' AND (
      EXISTS (SELECT 1 FROM public.stock_operation_lines l JOIN public.stock_operations o ON o.id = l.operation_id WHERE l.product_id = OLD.id AND o.status NOT IN ('DONE','CANCELED'))
      OR EXISTS (SELECT 1 FROM public.stock_adjustment_lines l JOIN public.stock_operations o ON o.id = l.operation_id WHERE l.product_id = OLD.id AND o.status NOT IN ('DONE','CANCELED'))) THEN
      RAISE EXCEPTION 'IN_USE: Product is used by an open operation';
    ELSIF TG_TABLE_NAME = 'warehouses' AND EXISTS (SELECT 1 FROM public.stock_operations WHERE warehouse_id = OLD.id AND status NOT IN ('DONE','CANCELED')) THEN
      RAISE EXCEPTION 'IN_USE: Warehouse has open operations';
    ELSIF TG_TABLE_NAME = 'locations' AND EXISTS (SELECT 1 FROM public.stock_operations WHERE (source_location_id = OLD.id OR destination_location_id = OLD.id) AND status NOT IN ('DONE','CANCELED')) THEN
      RAISE EXCEPTION 'IN_USE: Location is used by an open operation';
    END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER products_guard BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION public.guard_soft_delete();
CREATE TRIGGER warehouses_guard BEFORE UPDATE ON public.warehouses FOR EACH ROW EXECUTE FUNCTION public.guard_soft_delete();
CREATE TRIGGER locations_guard BEFORE UPDATE ON public.locations FOR EACH ROW EXECUTE FUNCTION public.guard_soft_delete();

REVOKE EXECUTE ON FUNCTION public._apply_move(public.stock_operations, bigint, bigint, numeric), public._reserve(bigint, bigint, numeric), public.next_reference(bigint, public.operation_type) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.create_operation(jsonb), public.update_operation(bigint, jsonb), public.confirm_operation(bigint), public.validate_operation(bigint), public.cancel_operation(bigint), public.set_stock(bigint, bigint, numeric), public.admin_update_user(uuid, public.app_role, bigint, boolean), public.refresh_waiting() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_operation(jsonb), public.update_operation(bigint, jsonb), public.confirm_operation(bigint), public.validate_operation(bigint), public.cancel_operation(bigint), public.set_stock(bigint, bigint, numeric), public.admin_update_user(uuid, public.app_role, bigint, boolean), public.refresh_waiting() TO authenticated;

INSERT INTO public.locations (warehouse_id, name, code, location_type) VALUES
  (NULL, 'Vendor', 'vendor', 'VENDOR'),
  (NULL, 'Customer', 'customer', 'CUSTOMER'),
  (NULL, 'Inventory Adjustment', 'adjust', 'ADJUSTMENT_VIRTUAL');
INSERT INTO public.warehouses (name, code, address) VALUES ('Main Warehouse', 'WH1', '12 Industrial Estate, Pune');
INSERT INTO public.locations (warehouse_id, name, code, location_type)
  SELECT id, 'Stock1', 'WH1/Stock1', 'INTERNAL'::public.location_type FROM public.warehouses WHERE code = 'WH1'
  UNION ALL SELECT id, 'Production Floor', 'WH1/Prod', 'INTERNAL'::public.location_type FROM public.warehouses WHERE code = 'WH1';
INSERT INTO public.units_of_measure (name, code) VALUES ('Units', 'pcs'), ('Kilogram', 'kg'), ('Meter', 'm');
INSERT INTO public.product_categories (name) VALUES ('Furniture'), ('Raw Material'), ('Electronics');
INSERT INTO public.products (name, sku, category_id, uom_id, unit_cost, reorder_min_qty)
  SELECT v.name, v.sku, c.id, u.id, v.cost, v.minq FROM (VALUES
    ('Office Desk','DESK001','Furniture','pcs',3000,5),
    ('Office Chair','CHAIR001','Furniture','pcs',1500,10),
    ('Steel Rod','STEEL001','Raw Material','kg',80,50),
    ('LED Monitor','MON001','Electronics','pcs',9000,3)) AS v(name,sku,cat,uom,cost,minq)
  JOIN public.product_categories c ON c.name = v.cat JOIN public.units_of_measure u ON u.code = v.uom;
INSERT INTO public.partners (name, type, email, address) VALUES
  ('Azure Interiors', 'SUPPLIER', 'sales@azure.example', '5 Market Road, Mumbai'),
  ('Steelworks Ltd', 'SUPPLIER', 'orders@steelworks.example', 'Plot 9, MIDC, Nashik'),
  ('Deco Addict', 'CUSTOMER', 'buy@decoaddict.example', '22 MG Road, Bengaluru'),
  ('Gemini Furniture', 'CUSTOMER', 'hello@gemini.example', '7 Park Street, Kolkata');